#cloud-config
autoinstall:
    version: 1
    identity:
        hostname: Webserver1
        username: ubuntu
        password: "$y$j9T$DlrH1eM3o7Q6FgGD9KNSY0$oJJepBuBgbkW.BDIVwJN5dU18iO7VR5yveWRr/9QRb9"
    refresh-installer:
        update: yes

package_upgrade: true
packages:
  - apache2
